#!/bin/bash

# Check argc
if [ "$#" -ne 1 ]; then
  echo "Invalid number of arguments"
  exit 1
fi

SCRIPT_DIR="${0::${#0}-8}"
DIR="$1"

# Check for missing / at the end of DIR
if [ "${DIR: -1}" != "/" ]; then
  DIR="${DIR}/"
fi

# Convert & upload
for FILE_PATH in "$DIR"*.md; do
  FILE_NAME=$(basename $FILE_PATH)
  HTML_NAME="${FILE_NAME::${#FILE_NAME}-3}.html"
  HTML_NAME=$(echo $HTML_NAME | tr -d ' ')

  cat "${SCRIPT_DIR}/intro.html" >>$HTML_NAME
  showdown makehtml -i "$FILE_PATH" >>$HTML_NAME
  cat "${SCRIPT_DIR}/outro.html" >>$HTML_NAME

  scp $HTML_NAME alex@192.168.2.99:/home/alex/md2html
done
